name: Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 1 * *'
  
jobs:
  make-bootstrap:
    name: Make Arch bootstrap
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
            bash make-bootstrap.sh
      - name: Set current date as env variable
        run: |
          echo "date=$(/bin/date -u '+%Y-%m-%d')" >> $GITHUB_ENV
      - name: Upload the release
        uses: "ncipollo/release-action@v1"
        with:
          tag: ${{ env.date }}
          name: "Arch Linux Bootstrap ${{ env.date }}"
          artifacts : "ArchWSLBootstrap-*.tar.gz"
          token: "${{ secrets.GITHUB_TOKEN }}"


